[tool.poetry]
name = "aesop"
version = "0.1.0"
description = "A CLI application for Metaphor data ingestion and upload"
authors = ["Metaphor <dev@metaphor.io>"]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.9.0"
rich = "^13.3.5"
aiohttp = "^3.9.5"
pydantic = "^2.0.0"
ariadne-codegen = "^0.14.0"

[tool.poetry.dev-dependencies]
black = "^24.2.0"
flake8 = "^7.0.0"
isort = "^5.11.0"
mypy = "^1.9.0"
pytest = "^8.2.1"
pytest-asyncio = "^0.23.7"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "strict"

[tool.black]
line-length = 100
target-version = ['py39']
extend-exclude = "src/aesop/graphql_models"

[tool.isort]
profile = "black"
line_length = 100
skip_glob = ["src/aesop/graphql_models/*"]

[tool.mypy]
ignore_missing_imports = true
strict = true
exclude = "src/aesop/graphql_models/"

[tool.ariadne-codegen]
schema_path = "schema.gql"
enable_custom_operations = true
target_package_name = "graphql_models_generated"
target_package_path = "./src/aesop"

# Add this section to create a CLI entry point
[tool.poetry.scripts]
aesop = "aesop.cli:app"
