---
name: Documentation

on:
  workflow_dispatch:
  workflow_call:

env:
  PYTHON_VERSION: 3.9
  TITLE: Metaphor CLI Documentation

permissions:
  contents: write # For writing to gh-pages branch
  actions: read # https://github.com/softprops/turnstyle?tab=readme-ov-file#required-permissions

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Generate typer markdown documentation
        run: typer aesop/app.py utils docs --name "aesop" --output docs/index.md --title '${{ env.TITLE }}'

      - name: Build MkDocs site
        run: mkdocs build

      - name: Set git user
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'release-bot@users.noreply.github.com'

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
