---
name: CI

env:
  PYTHON_VERSION: 3.9
  CONFIG: qa
  METAPHOR_API_KEY: meta-03f22b24-faaf-4b0e-9ab7-27e91701a7d1

# Run this build workflow for every new PR
on:
  pull_request:
    branches: [main]
  merge_group:

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Check format
        run: poetry run poe check-format

  check-type:
    name: Check typing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Check type
        run: poetry run poe check-type

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Run tests
        run: poetry run pytest tests
