name: Run tests and upload coverage

on:
  push:

env:
  PYTHON_VERSION: 3.9
  URL: ${{ vars.METAPHOR_URL }}
  METAPHOR_API_KEY: ${{ secrets.METAPHOR_API_KEY }}

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Run tests
        run: |
          poetry run pytest --cov=aesop --cov-report=xml tests

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}